// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTdenblFQSs041dBRGriag_YNV8jgmInE',
    appId: '1:174705748627:android:b8b95ac2b2c16033a3bb66',
    messagingSenderId: '174705748627',
    projectId: 'libecity-app',
    storageBucket: 'libecity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPCIWrEBuOn37DeEyzZsjDwIAIsjfiBV0',
    appId: '1:174705748627:ios:e143b763d89f55c5a3bb66',
    messagingSenderId: '174705748627',
    projectId: 'libecity-app',
    storageBucket: 'libecity-app.firebasestorage.app',
    iosBundleId: 'com.libecity.libecityApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaD7Xl0mHSXUciUyoLAhsGulcFq7VZzoI',
    appId: '1:174705748627:web:74296f12ddb4cc3da3bb66',
    messagingSenderId: '174705748627',
    projectId: 'libecity-app',
    authDomain: 'libecity-app.firebaseapp.com',
    storageBucket: 'libecity-app.firebasestorage.app',
  );
}
